/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesCarLoanRouteImport } from './routes/services/car-loan'
import { Route as ServicesChildEducationPlanningRouteImport } from './routes/services/child-education-planning'
import { Route as ServicesEducationLoanRouteImport } from './routes/services/education-loan'
import { Route as ServicesFinancialLiteracyRouteImport } from './routes/services/financial-literacy'
import { Route as ServicesHealthInsuranceRouteImport } from './routes/services/health-insurance'
import { Route as ServicesHomeLoanRouteImport } from './routes/services/home-loan'
import { Route as ServicesLoansRouteImport } from './routes/services/loans'
import { Route as ServicesPersonalLoanRouteImport } from './routes/services/personal-loan'
import { Route as ServicesRetirementPlanningRouteImport } from './routes/services/retirement-planning'
import { Route as ServicesSipWealthCreationRouteImport } from './routes/services/sip-wealth-creation'
import { Route as ServicesTermPlanRouteImport } from './routes/services/term-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCarLoanRoute = ServicesCarLoanRouteImport.update({
  id: '/car-loan',
  path: '/car-loan',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesChildEducationPlanningRoute =
  ServicesChildEducationPlanningRouteImport.update({
    id: '/child-education-planning',
    path: '/child-education-planning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesEducationLoanRoute = ServicesEducationLoanRouteImport.update({
  id: '/education-loan',
  path: '/education-loan',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFinancialLiteracyRoute =
  ServicesFinancialLiteracyRouteImport.update({
    id: '/financial-literacy',
    path: '/financial-literacy',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHealthInsuranceRoute = ServicesHealthInsuranceRouteImport.update({
  id: '/health-insurance',
  path: '/health-insurance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHomeLoanRoute = ServicesHomeLoanRouteImport.update({
  id: '/home-loan',
  path: '/home-loan',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLoansRoute = ServicesLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPersonalLoanRoute = ServicesPersonalLoanRouteImport.update({
  id: '/personal-loan',
  path: '/personal-loan',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRetirementPlanningRoute =
  ServicesRetirementPlanningRouteImport.update({
    id: '/retirement-planning',
    path: '/retirement-planning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSipWealthCreationRoute =
  ServicesSipWealthCreationRouteImport.update({
    id: '/sip-wealth-creation',
    path: '/sip-wealth-creation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTermPlanRoute = ServicesTermPlanRouteImport.update({
  id: '/term-plan',
  path: '/term-plan',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/car-loan': typeof ServicesCarLoanRoute
  '/services/child-education-planning': typeof ServicesChildEducationPlanningRoute
  '/services/education-loan': typeof ServicesEducationLoanRoute
  '/services/financial-literacy': typeof ServicesFinancialLiteracyRoute
  '/services/health-insurance': typeof ServicesHealthInsuranceRoute
  '/services/home-loan': typeof ServicesHomeLoanRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/personal-loan': typeof ServicesPersonalLoanRoute
  '/services/retirement-planning': typeof ServicesRetirementPlanningRoute
  '/services/sip-wealth-creation': typeof ServicesSipWealthCreationRoute
  '/services/term-plan': typeof ServicesTermPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/car-loan': typeof ServicesCarLoanRoute
  '/services/child-education-planning': typeof ServicesChildEducationPlanningRoute
  '/services/education-loan': typeof ServicesEducationLoanRoute
  '/services/financial-literacy': typeof ServicesFinancialLiteracyRoute
  '/services/health-insurance': typeof ServicesHealthInsuranceRoute
  '/services/home-loan': typeof ServicesHomeLoanRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/personal-loan': typeof ServicesPersonalLoanRoute
  '/services/retirement-planning': typeof ServicesRetirementPlanningRoute
  '/services/sip-wealth-creation': typeof ServicesSipWealthCreationRoute
  '/services/term-plan': typeof ServicesTermPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/car-loan': typeof ServicesCarLoanRoute
  '/services/child-education-planning': typeof ServicesChildEducationPlanningRoute
  '/services/education-loan': typeof ServicesEducationLoanRoute
  '/services/financial-literacy': typeof ServicesFinancialLiteracyRoute
  '/services/health-insurance': typeof ServicesHealthInsuranceRoute
  '/services/home-loan': typeof ServicesHomeLoanRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/personal-loan': typeof ServicesPersonalLoanRoute
  '/services/retirement-planning': typeof ServicesRetirementPlanningRoute
  '/services/sip-wealth-creation': typeof ServicesSipWealthCreationRoute
  '/services/term-plan': typeof ServicesTermPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/services/car-loan'
    | '/services/child-education-planning'
    | '/services/education-loan'
    | '/services/financial-literacy'
    | '/services/health-insurance'
    | '/services/home-loan'
    | '/services/loans'
    | '/services/personal-loan'
    | '/services/retirement-planning'
    | '/services/sip-wealth-creation'
    | '/services/term-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/services/car-loan'
    | '/services/child-education-planning'
    | '/services/education-loan'
    | '/services/financial-literacy'
    | '/services/health-insurance'
    | '/services/home-loan'
    | '/services/loans'
    | '/services/personal-loan'
    | '/services/retirement-planning'
    | '/services/sip-wealth-creation'
    | '/services/term-plan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/services/car-loan'
    | '/services/child-education-planning'
    | '/services/education-loan'
    | '/services/financial-literacy'
    | '/services/health-insurance'
    | '/services/home-loan'
    | '/services/loans'
    | '/services/personal-loan'
    | '/services/retirement-planning'
    | '/services/sip-wealth-creation'
    | '/services/term-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/car-loan': {
      id: '/services/car-loan'
      path: '/car-loan'
      fullPath: '/services/car-loan'
      preLoaderRoute: typeof ServicesCarLoanRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/child-education-planning': {
      id: '/services/child-education-planning'
      path: '/child-education-planning'
      fullPath: '/services/child-education-planning'
      preLoaderRoute: typeof ServicesChildEducationPlanningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/education-loan': {
      id: '/services/education-loan'
      path: '/education-loan'
      fullPath: '/services/education-loan'
      preLoaderRoute: typeof ServicesEducationLoanRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/financial-literacy': {
      id: '/services/financial-literacy'
      path: '/financial-literacy'
      fullPath: '/services/financial-literacy'
      preLoaderRoute: typeof ServicesFinancialLiteracyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/health-insurance': {
      id: '/services/health-insurance'
      path: '/health-insurance'
      fullPath: '/services/health-insurance'
      preLoaderRoute: typeof ServicesHealthInsuranceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home-loan': {
      id: '/services/home-loan'
      path: '/home-loan'
      fullPath: '/services/home-loan'
      preLoaderRoute: typeof ServicesHomeLoanRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/loans': {
      id: '/services/loans'
      path: '/loans'
      fullPath: '/services/loans'
      preLoaderRoute: typeof ServicesLoansRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/personal-loan': {
      id: '/services/personal-loan'
      path: '/personal-loan'
      fullPath: '/services/personal-loan'
      preLoaderRoute: typeof ServicesPersonalLoanRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/retirement-planning': {
      id: '/services/retirement-planning'
      path: '/retirement-planning'
      fullPath: '/services/retirement-planning'
      preLoaderRoute: typeof ServicesRetirementPlanningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sip-wealth-creation': {
      id: '/services/sip-wealth-creation'
      path: '/sip-wealth-creation'
      fullPath: '/services/sip-wealth-creation'
      preLoaderRoute: typeof ServicesSipWealthCreationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/term-plan': {
      id: '/services/term-plan'
      path: '/term-plan'
      fullPath: '/services/term-plan'
      preLoaderRoute: typeof ServicesTermPlanRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCarLoanRoute: typeof ServicesCarLoanRoute
  ServicesChildEducationPlanningRoute: typeof ServicesChildEducationPlanningRoute
  ServicesEducationLoanRoute: typeof ServicesEducationLoanRoute
  ServicesFinancialLiteracyRoute: typeof ServicesFinancialLiteracyRoute
  ServicesHealthInsuranceRoute: typeof ServicesHealthInsuranceRoute
  ServicesHomeLoanRoute: typeof ServicesHomeLoanRoute
  ServicesLoansRoute: typeof ServicesLoansRoute
  ServicesPersonalLoanRoute: typeof ServicesPersonalLoanRoute
  ServicesRetirementPlanningRoute: typeof ServicesRetirementPlanningRoute
  ServicesSipWealthCreationRoute: typeof ServicesSipWealthCreationRoute
  ServicesTermPlanRoute: typeof ServicesTermPlanRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCarLoanRoute: ServicesCarLoanRoute,
  ServicesChildEducationPlanningRoute: ServicesChildEducationPlanningRoute,
  ServicesEducationLoanRoute: ServicesEducationLoanRoute,
  ServicesFinancialLiteracyRoute: ServicesFinancialLiteracyRoute,
  ServicesHealthInsuranceRoute: ServicesHealthInsuranceRoute,
  ServicesHomeLoanRoute: ServicesHomeLoanRoute,
  ServicesLoansRoute: ServicesLoansRoute,
  ServicesPersonalLoanRoute: ServicesPersonalLoanRoute,
  ServicesRetirementPlanningRoute: ServicesRetirementPlanningRoute,
  ServicesSipWealthCreationRoute: ServicesSipWealthCreationRoute,
  ServicesTermPlanRoute: ServicesTermPlanRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
